# This workflow will build a package using Maven and then publish the architecture.pdf as artifact

name: Build

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive pdf
      uses: actions/upload-artifact@v4
      with:
        name: architecture (pdf)
        path: target/generated-docs/architecture.pdf
    - name: Archive html
      uses: actions/upload-artifact@v4
      with:
        name: architecture (html)
        path: target/generated-docs/architecture.html    